[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pyright = "^1.1.371"
pulumi = "^3.124.0"
pulumi-gcp = "^7.30.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"